// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp7Ju5yrKaXYvWpU7uSJKBPFDxA30ta_M',
    appId: '1:20978497970:web:4edb72399aa8f182394cab',
    messagingSenderId: '20978497970',
    projectId: 'auto-revive-b',
    authDomain: 'auto-revive-b.firebaseapp.com',
    storageBucket: 'auto-revive-b.firebasestorage.app',
    measurementId: 'G-W4F6QX592V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdsj305TmbZnVY9juCwCigeT0hsUfGzwY',
    appId: '1:20978497970:android:81683176ffa231f5394cab',
    messagingSenderId: '20978497970',
    projectId: 'auto-revive-b',
    storageBucket: 'auto-revive-b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQMVZ-PZG0blHAnitPJQgsVMaKys7oAQ',
    appId: '1:20978497970:ios:f1fd9345b8628774394cab',
    messagingSenderId: '20978497970',
    projectId: 'auto-revive-b',
    storageBucket: 'auto-revive-b.firebasestorage.app',
    iosBundleId: 'com.fixitprosllc.fixitprosllc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQMVZ-PZG0blHAnitPJQgsVMaKys7oAQ',
    appId: '1:20978497970:ios:f1fd9345b8628774394cab',
    messagingSenderId: '20978497970',
    projectId: 'auto-revive-b',
    storageBucket: 'auto-revive-b.firebasestorage.app',
    iosBundleId: 'com.fixitprosllc.fixitprosllc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp7Ju5yrKaXYvWpU7uSJKBPFDxA30ta_M',
    appId: '1:20978497970:web:c1ae90c0545b035f394cab',
    messagingSenderId: '20978497970',
    projectId: 'auto-revive-b',
    authDomain: 'auto-revive-b.firebaseapp.com',
    storageBucket: 'auto-revive-b.firebasestorage.app',
    measurementId: 'G-Q29B6GQNQC',
  );
}
